image: Ubuntu
environment:
  nodejs_version: "16"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build_script:
  - npm run build
test_script:
  - npm test
  - npm run e2e
on_success:
  - git config --global credential.helper store
  - git config --global user.email "your-email@example.com"
  - git config --global user.name "Your Name"
  - npm run deploy